/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazModulosCaptura;

import conexion.consultasBD;
import javax.swing.JOptionPane;

/**
 *
 * @author bruce
 */
public class capturaCliente extends javax.swing.JFrame {

    /**
     * Creates new form registrarCliente
     */
    public capturaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCliente = new javax.swing.JPanel();
        btnClienteRegistrar = new javax.swing.JButton();
        clienteTxtNombre = new javax.swing.JTextField();
        lblClienteNombre = new javax.swing.JLabel();
        lblClienteDireccion = new javax.swing.JLabel();
        clienteTxtDireccion = new javax.swing.JTextField();
        btnClienteCerrar = new javax.swing.JButton();
        lblClienteCP = new javax.swing.JLabel();
        clienteTxtCP = new javax.swing.JTextField();
        clienteTxtRFC = new javax.swing.JTextField();
        lblClienteRFC = new javax.swing.JLabel();
        clienteTxtTelefono = new javax.swing.JTextField();
        lblClienteTelefono = new javax.swing.JLabel();
        lblClienteCorreo = new javax.swing.JLabel();
        clienteTxtCorreo = new javax.swing.JTextField();
        lblClienteTitulo = new javax.swing.JLabel();
        cboxContador = new javax.swing.JComboBox<>();
        lblClienteContador = new javax.swing.JLabel();
        lblClienteReg = new javax.swing.JLabel();
        cboxRegimenFiscal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClienteRegistrar.setText("Registrar");
        btnClienteRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteRegistrarActionPerformed(evt);
            }
        });

        clienteTxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTxtNombreActionPerformed(evt);
            }
        });

        lblClienteNombre.setText("Nombre:");

        lblClienteDireccion.setText("Direccion:");

        btnClienteCerrar.setText("Cerrar");
        btnClienteCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteCerrarActionPerformed(evt);
            }
        });

        lblClienteCP.setText("Codigo Postal:");

        clienteTxtCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTxtCPActionPerformed(evt);
            }
        });

        clienteTxtRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTxtRFCActionPerformed(evt);
            }
        });

        lblClienteRFC.setText("RFC");

        clienteTxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTxtTelefonoActionPerformed(evt);
            }
        });

        lblClienteTelefono.setText("Telefono:");

        lblClienteCorreo.setText("Correo:");

        clienteTxtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteTxtCorreoActionPerformed(evt);
            }
        });

        lblClienteTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblClienteTitulo.setText("Registro de Cliente");

        cboxContador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxContadorActionPerformed(evt);
            }
        });

        lblClienteContador.setText("Contador:");

        lblClienteReg.setText("Regimen Fiscal:");

        cboxRegimenFiscal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxRegimenFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxRegimenFiscalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(lblClienteTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(clienteTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(lblClienteRFC)
                                .addGap(18, 18, 18)
                                .addComponent(clienteTxtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelClienteLayout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(btnClienteRegistrar)
                                    .addGap(42, 42, 42)
                                    .addComponent(btnClienteCerrar))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteLayout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(clienteTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblClienteNombre)
                                .addGroup(panelClienteLayout.createSequentialGroup()
                                    .addComponent(lblClienteDireccion)
                                    .addGap(18, 18, 18)
                                    .addComponent(clienteTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(lblClienteCP)
                                .addGap(18, 18, 18)
                                .addComponent(clienteTxtCP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblClienteReg)
                            .addComponent(lblClienteContador)
                            .addComponent(lblClienteCorreo))
                        .addGap(35, 35, 35)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboxRegimenFiscal, 0, 129, Short.MAX_VALUE)
                            .addComponent(clienteTxtCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxContador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(lblClienteTitulo)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblClienteTitulo)
                .addGap(31, 31, 31)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteNombre)
                    .addComponent(lblClienteCorreo)
                    .addComponent(clienteTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteTxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteTxtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clienteTxtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClienteRFC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clienteTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClienteTelefono)))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxRegimenFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClienteReg))
                        .addGap(15, 15, 15)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClienteContador)
                            .addComponent(cboxContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteRegistrar)
                    .addComponent(btnClienteCerrar))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteRegistrarActionPerformed
        // TODO add your handling code here:
        
      
        
    }//GEN-LAST:event_btnClienteRegistrarActionPerformed

    private void clienteTxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTxtNombreActionPerformed

    private void btnClienteCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnClienteCerrarActionPerformed

    private void clienteTxtCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTxtCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTxtCPActionPerformed

    private void clienteTxtRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTxtRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTxtRFCActionPerformed

    private void clienteTxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTxtTelefonoActionPerformed

    private void clienteTxtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteTxtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteTxtCorreoActionPerformed

    private void cboxContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxContadorActionPerformed

    private void cboxRegimenFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRegimenFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxRegimenFiscalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(capturaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(capturaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(capturaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(capturaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new capturaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteCerrar;
    private javax.swing.JButton btnClienteRegistrar;
    private javax.swing.JComboBox<String> cboxContador;
    private javax.swing.JComboBox<String> cboxRegimenFiscal;
    private javax.swing.JTextField clienteTxtCP;
    private javax.swing.JTextField clienteTxtCorreo;
    private javax.swing.JTextField clienteTxtDireccion;
    private javax.swing.JTextField clienteTxtNombre;
    private javax.swing.JTextField clienteTxtRFC;
    private javax.swing.JTextField clienteTxtTelefono;
    private javax.swing.JLabel lblClienteCP;
    private javax.swing.JLabel lblClienteContador;
    private javax.swing.JLabel lblClienteCorreo;
    private javax.swing.JLabel lblClienteDireccion;
    private javax.swing.JLabel lblClienteNombre;
    private javax.swing.JLabel lblClienteRFC;
    private javax.swing.JLabel lblClienteReg;
    private javax.swing.JLabel lblClienteTelefono;
    private javax.swing.JLabel lblClienteTitulo;
    private javax.swing.JPanel panelCliente;
    // End of variables declaration//GEN-END:variables
}
