/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazModulosCaptura;

/**
 *
 * @author bruce
 */
public class capturaCompradores extends javax.swing.JFrame {

    /**
     * Creates new form capturaCompradores
     */
    public capturaCompradores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompradoresTitulo = new javax.swing.JLabel();
        lblCompradoresNombre = new javax.swing.JLabel();
        lblCompradoresDireccion = new javax.swing.JLabel();
        lblCompradoresTelefono = new javax.swing.JLabel();
        lblCompradoresRFC = new javax.swing.JLabel();
        lblCompradoresCP = new javax.swing.JLabel();
        btnCompradoresRegistrar = new javax.swing.JButton();
        btnCompradoresCerrar = new javax.swing.JButton();
        txtCompradoresDireccion = new javax.swing.JTextField();
        txtCompradoresNombre = new javax.swing.JTextField();
        txtCompradoresTelefono = new javax.swing.JTextField();
        txtCompradoresRFC = new javax.swing.JTextField();
        txtCompradoresCP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompradoresTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblCompradoresTitulo.setText("Registro de Compradores");

        lblCompradoresNombre.setText("Nombre:");

        lblCompradoresDireccion.setText("Direccion:");

        lblCompradoresTelefono.setText("Telefono:");

        lblCompradoresRFC.setText("RFC:");

        lblCompradoresCP.setText("Codigo Postal:");

        btnCompradoresRegistrar.setText("Registrar");
        btnCompradoresRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompradoresRegistrarActionPerformed(evt);
            }
        });

        btnCompradoresCerrar.setText("Cerrar");
        btnCompradoresCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompradoresCerrarActionPerformed(evt);
            }
        });

        txtCompradoresDireccion.setText("jTextField1");

        txtCompradoresNombre.setText("jTextField1");

        txtCompradoresTelefono.setText("jTextField1");

        txtCompradoresRFC.setText("jTextField1");

        txtCompradoresCP.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnCompradoresRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCompradoresCerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCompradoresRFC)
                                    .addComponent(lblCompradoresCP)
                                    .addComponent(lblCompradoresTelefono)
                                    .addComponent(lblCompradoresDireccion)
                                    .addComponent(lblCompradoresNombre))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCompradoresCP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompradoresRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompradoresTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompradoresDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompradoresNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblCompradoresTitulo)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCompradoresTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCompradoresNombre)
                    .addComponent(txtCompradoresNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCompradoresDireccion)
                    .addComponent(txtCompradoresDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCompradoresTelefono)
                    .addComponent(txtCompradoresTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCompradoresRFC)
                    .addComponent(txtCompradoresRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCompradoresCP)
                    .addComponent(txtCompradoresCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompradoresCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompradoresRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompradoresRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompradoresRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompradoresRegistrarActionPerformed

    private void btnCompradoresCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompradoresCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCompradoresCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(capturaCompradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(capturaCompradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(capturaCompradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(capturaCompradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new capturaCompradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompradoresCerrar;
    private javax.swing.JButton btnCompradoresRegistrar;
    private javax.swing.JLabel lblCompradoresCP;
    private javax.swing.JLabel lblCompradoresDireccion;
    private javax.swing.JLabel lblCompradoresNombre;
    private javax.swing.JLabel lblCompradoresRFC;
    private javax.swing.JLabel lblCompradoresTelefono;
    private javax.swing.JLabel lblCompradoresTitulo;
    private javax.swing.JTextField txtCompradoresCP;
    private javax.swing.JTextField txtCompradoresDireccion;
    private javax.swing.JTextField txtCompradoresNombre;
    private javax.swing.JTextField txtCompradoresRFC;
    private javax.swing.JTextField txtCompradoresTelefono;
    // End of variables declaration//GEN-END:variables
}
