/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazModulosCaptura;

import conexion.consultasBD;
import javax.swing.JOptionPane;

/**
 *
 * @author bruce
 */
public class capturaComplementoPago extends javax.swing.JFrame {

    /**
     * Creates new form capturaComplementoPago
     */
    public capturaComplementoPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComplementoTitulo = new javax.swing.JLabel();
        lblComplementoFolio = new javax.swing.JLabel();
        lblComplementoFactura = new javax.swing.JLabel();
        cboxComplementoFactura = new javax.swing.JComboBox<>();
        txtComplementoFolio = new javax.swing.JTextField();
        btnComplementoCerrar = new javax.swing.JButton();
        btnComplementoRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblComplementoTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblComplementoTitulo.setText("Registro de Complementos");

        lblComplementoFolio.setText("Folio de Complemento:");

        lblComplementoFactura.setText("Factura Relacionada:");

        cboxComplementoFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxComplementoFacturaMouseClicked(evt);
            }
        });
        cboxComplementoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxComplementoFacturaActionPerformed(evt);
            }
        });

        btnComplementoCerrar.setText("Cerrar");
        btnComplementoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplementoCerrarActionPerformed(evt);
            }
        });

        btnComplementoRegistrar.setText("Registrar");
        btnComplementoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplementoRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblComplementoTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComplementoFolio)
                            .addComponent(lblComplementoFactura, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplementoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxComplementoFactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnComplementoRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComplementoCerrar)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblComplementoTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplementoFolio)
                    .addComponent(txtComplementoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxComplementoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplementoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComplementoCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComplementoRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComplementoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplementoCerrarActionPerformed
        // TODO add your handling code here:
        interfazCaptura verformulario = new interfazCaptura();
        
        verformulario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnComplementoCerrarActionPerformed

    private void btnComplementoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplementoRegistrarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnComplementoRegistrarActionPerformed

    private void cboxComplementoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxComplementoFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxComplementoFacturaActionPerformed

    private void cboxComplementoFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxComplementoFacturaMouseClicked
        // TODO add your handling code here:
        
       String mensaje = "";
        
        try{
        consultasBD cargarComboBox = new consultasBD();
        cboxComplementoFactura.removeAllItems();
        cargarComboBox.consultaFacturasCliente(cboxComplementoFactura);
        if(cboxComplementoFactura.getItemCount() == 0){
            mensaje = "Es necesario capturar primero la factura";
            JOptionPane.showMessageDialog(null, mensaje);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cboxComplementoFacturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(capturaComplementoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(capturaComplementoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(capturaComplementoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(capturaComplementoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new capturaComplementoPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplementoCerrar;
    private javax.swing.JButton btnComplementoRegistrar;
    private javax.swing.JComboBox<String> cboxComplementoFactura;
    private javax.swing.JLabel lblComplementoFactura;
    private javax.swing.JLabel lblComplementoFolio;
    private javax.swing.JLabel lblComplementoTitulo;
    private javax.swing.JTextField txtComplementoFolio;
    // End of variables declaration//GEN-END:variables
}
