/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazModulosCaptura;

import clases.compras;
import conexion.consultasBD;
import javax.swing.JOptionPane;

/**
 *
 * @author bruce
 */
public class capturaCompras extends javax.swing.JFrame {

    /**
     * Creates new form capturaComprasç
     */
    public capturaCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompraTitulo = new javax.swing.JLabel();
        lblCompraNoCompra = new javax.swing.JLabel();
        lblCompraFechaLiq = new javax.swing.JLabel();
        lblCompraFechaVenc = new javax.swing.JLabel();
        lblCompraPacas = new javax.swing.JLabel();
        lblCompraTotal = new javax.swing.JLabel();
        txtCompraNoCompra = new javax.swing.JTextField();
        txtCompraFechaLiq = new javax.swing.JTextField();
        txtCompraPacas = new javax.swing.JTextField();
        txtCompraFechaVenc = new javax.swing.JTextField();
        txtCompraTotal = new javax.swing.JTextField();
        lblCompraCliente = new javax.swing.JLabel();
        cboxCompraCliente = new javax.swing.JComboBox<>();
        btnCompraRegistrar = new javax.swing.JButton();
        btnCompraCerrar = new javax.swing.JButton();
        lblComprasComprador = new javax.swing.JLabel();
        cboxComprasComprador = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCompraTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblCompraTitulo.setText("Registro de Compras");

        lblCompraNoCompra.setText("No. Compra:");

        lblCompraFechaLiq.setText("Fecha Liquidacion:");

        lblCompraFechaVenc.setText("Fecha de Vencimiento:");

        lblCompraPacas.setText("Pacas:");

        lblCompraTotal.setText("Total:");

        txtCompraPacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompraPacasActionPerformed(evt);
            }
        });

        lblCompraCliente.setText("Cliente:");

        cboxCompraCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxCompraClienteMouseClicked(evt);
            }
        });
        cboxCompraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCompraClienteActionPerformed(evt);
            }
        });

        btnCompraRegistrar.setText("Registrar");
        btnCompraRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraRegistrarActionPerformed(evt);
            }
        });

        btnCompraCerrar.setText("Cerrar");
        btnCompraCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraCerrarActionPerformed(evt);
            }
        });

        lblComprasComprador.setText("Comprador: ");

        cboxComprasComprador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxComprasCompradorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCompraTitulo)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblComprasComprador)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(179, 179, 179)
                                    .addComponent(lblCompraTotal))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(lblCompraPacas))
                                        .addComponent(lblCompraNoCompra))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCompraNoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCompraPacas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(btnCompraRegistrar)
                            .addGap(24, 24, 24)
                            .addComponent(btnCompraCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblCompraCliente))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboxCompraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompraTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCompraFechaVenc)
                            .addComponent(lblCompraFechaLiq))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCompraFechaLiq, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(txtCompraFechaVenc)))
                    .addComponent(cboxComprasComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblCompraTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCompraNoCompra)
                        .addComponent(txtCompraNoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCompraFechaLiq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCompraFechaLiq, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCompraPacas)
                        .addComponent(txtCompraPacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCompraFechaVenc)
                        .addComponent(txtCompraFechaVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompraTotal)
                    .addComponent(txtCompraTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompraCliente)
                    .addComponent(cboxCompraCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxComprasComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComprasComprador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompraRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompraCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompraCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraCerrarActionPerformed
        // TODO add your handling code here:
        interfazCaptura verformulario = new interfazCaptura();
        
        verformulario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCompraCerrarActionPerformed

    private void btnCompraRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraRegistrarActionPerformed
        // TODO add your handling code here:
        Boolean guardar = true;
        String mensaje = "";
        
        try{
            
        String noCompra = txtCompraNoCompra.getText();  
        String fechaLiq = txtCompraFechaLiq.getText();
        String fechaVenc = txtCompraFechaVenc.getText();
        int pacas = Integer.parseInt(txtCompraPacas.getText());
        float total = Float.parseFloat(txtCompraTotal.getText());
         //int total = Integer.parseInt(txtCompraTotal.getText());
         
       if (fechaLiq.length()==0){
            guardar = false;
            mensaje+="Escriba la fecha de liquidacion, por favor\n";
        }
        if (fechaVenc.length()==0){
            guardar = false;
            mensaje+="Escriba la fecha de vencimiento, por favor\n";
        }
        if (noCompra.length()==0){
            guardar = false;
            mensaje+="Escriba el numero de compra, por favor\n";
        }
        if (pacas==0){
            guardar = false;
            mensaje+="Escriba la cantidad de Pacas, por favor\n";
        }
        if (total == 0){
        guardar = false;
        mensaje+="Escriba el total de la compra, por favor\n";
        }

            String c = (String) cboxCompraCliente.getSelectedItem();
            char d = c.charAt(0);
            int cliente = Character.getNumericValue(d);
            
            String f = (String) cboxComprasComprador.getSelectedItem();
            char g = f.charAt(0);
            int comprador = Character.getNumericValue(g);
            
            
        if(guardar){
           consultasBD consulta = new consultasBD();
           JOptionPane.showMessageDialog(null, "compra: " +  noCompra + "\n" + "Fecha de Venc: " + fechaVenc + "\n" + "Fecha de Liq: " + fechaLiq + "\n" + "cliente: " + cliente + "\n" + "pacas: " + pacas + "\n" + "comprador: " + comprador + "\n" + "total: " + total);
           compras compras = new compras(noCompra, fechaVenc, fechaLiq, cliente, pacas, (int) total, comprador);
           
           consulta.registrarCompra(compras);
           
           txtCompraFechaLiq.setText("");
           txtCompraFechaVenc.setText("");
           txtCompraNoCompra.setText("");
           txtCompraPacas.setText("");
           txtCompraTotal.setText("");
           
        }
           else{
               JOptionPane.showMessageDialog(null, mensaje);
           }
     }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }

    }//GEN-LAST:event_btnCompraRegistrarActionPerformed

    private void txtCompraPacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompraPacasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompraPacasActionPerformed

    private void cboxCompraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCompraClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCompraClienteActionPerformed

    private void cboxCompraClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxCompraClienteMouseClicked
        // TODO add your handling code here:
        String mensaje = "";
        
        try{
        consultasBD cargarComboBox = new consultasBD();
        cboxCompraCliente.removeAllItems();
        cargarComboBox.consultaClientes(cboxCompraCliente);
        if(cboxCompraCliente.getItemCount() == 0){
            mensaje = "Es necesario capturar primero el cliente";
            JOptionPane.showMessageDialog(null, mensaje);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cboxCompraClienteMouseClicked

    private void cboxComprasCompradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxComprasCompradorMouseClicked
        // TODO add your handling code here:
        String mensaje = "";
        
        try{
        consultasBD cargarComboBox = new consultasBD();
        cboxComprasComprador.removeAllItems();
        cargarComboBox.consultaCompradores(cboxComprasComprador);
        if(cboxComprasComprador.getItemCount() == 0){
            mensaje = "Es necesario capturar primero el comprador";
            JOptionPane.showMessageDialog(null, mensaje);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cboxComprasCompradorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(capturaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(capturaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(capturaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(capturaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new capturaCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompraCerrar;
    private javax.swing.JButton btnCompraRegistrar;
    private javax.swing.JComboBox<String> cboxCompraCliente;
    private javax.swing.JComboBox<String> cboxComprasComprador;
    private javax.swing.JLabel lblCompraCliente;
    private javax.swing.JLabel lblCompraFechaLiq;
    private javax.swing.JLabel lblCompraFechaVenc;
    private javax.swing.JLabel lblCompraNoCompra;
    private javax.swing.JLabel lblCompraPacas;
    private javax.swing.JLabel lblCompraTitulo;
    private javax.swing.JLabel lblCompraTotal;
    private javax.swing.JLabel lblComprasComprador;
    private javax.swing.JTextField txtCompraFechaLiq;
    private javax.swing.JTextField txtCompraFechaVenc;
    private javax.swing.JTextField txtCompraNoCompra;
    private javax.swing.JTextField txtCompraPacas;
    private javax.swing.JTextField txtCompraTotal;
    // End of variables declaration//GEN-END:variables
}
