/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazModulosCaptura;

import clases.facturas;
import clases.pagos;
import conexion.consultasBD;
import javax.swing.JOptionPane;

/**
 *
 * @author bruce
 */
public class capturaFacturas extends javax.swing.JFrame {

    /**
     * Creates new form capturaFacturas
     */
    public capturaFacturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFacturasTitulo = new javax.swing.JLabel();
        lblFacturasFolio = new javax.swing.JLabel();
        lblFacturasCliente = new javax.swing.JLabel();
        cboxFacturasCliente = new javax.swing.JComboBox<>();
        txtFacturasFolio = new javax.swing.JTextField();
        txtFacturasTotal = new javax.swing.JTextField();
        lblFacturasTotal = new javax.swing.JLabel();
        btnFacturasCerrar = new javax.swing.JButton();
        btnFacturasRegistrar = new javax.swing.JButton();
        lblFacturaCompra = new javax.swing.JLabel();
        cboxCompraFacturas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFacturasTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblFacturasTitulo.setText("Registro de Facturas");

        lblFacturasFolio.setText("Folio de Factura:");

        lblFacturasCliente.setText("Cliente Relacionado:");

        cboxFacturasCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxFacturasClienteMouseClicked(evt);
            }
        });
        cboxFacturasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxFacturasClienteActionPerformed(evt);
            }
        });

        lblFacturasTotal.setText("Total:");

        btnFacturasCerrar.setText("Cerrar");
        btnFacturasCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasCerrarActionPerformed(evt);
            }
        });

        btnFacturasRegistrar.setText("Registrar");
        btnFacturasRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasRegistrarActionPerformed(evt);
            }
        });

        lblFacturaCompra.setText("Compra Relacionada:");

        cboxCompraFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxCompraFacturasMouseClicked(evt);
            }
        });
        cboxCompraFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCompraFacturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblFacturasTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblFacturasTotal)
                        .addGap(18, 18, 18)
                        .addComponent(txtFacturasTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFacturaCompra)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFacturasCliente)
                                .addComponent(lblFacturasFolio)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFacturasFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxFacturasCliente, 0, 214, Short.MAX_VALUE)
                            .addComponent(cboxCompraFacturas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnFacturasRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFacturasCerrar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblFacturasTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacturasFolio)
                    .addComponent(txtFacturasFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFacturasCliente)
                    .addComponent(cboxFacturasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFacturaCompra)
                    .addComponent(cboxCompraFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacturasTotal)
                    .addComponent(txtFacturasTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFacturasCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacturasRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturasCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasCerrarActionPerformed
        // TODO add your handling code here:
        interfazCaptura verformulario = new interfazCaptura();
        
        verformulario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFacturasCerrarActionPerformed

    private void btnFacturasRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasRegistrarActionPerformed
        // TODO add your handling code here:
        
        Boolean guardar = true;
        String mensaje = "";
        String s = "";
        String t = "";
        
        try{
            
        String folioFactura = txtFacturasFolio.getText();  
        float totalFactura = Float.parseFloat(txtFacturasTotal.getText());
        int compraRelacionada = 0;
        int clienteRelacionado = 0;
        
       if (folioFactura.length()==0){
            guardar = false;
            mensaje+="Escriba el flio de la factura, por favor\n";
        }
        if (totalFactura==0){
            guardar = false;
            mensaje+="Escriba el monto total en DLS, por favor\n";
        }

            String c = (String) cboxFacturasCliente.getSelectedItem();
            char d = c.charAt(0);
            char e = c.charAt(1);
            
            if(Character.isDigit(e)){
                
                t = new StringBuilder().append(d).append(e).toString();
                clienteRelacionado = Integer.parseInt(t);
            }
            else{
                t = new StringBuilder().append(d).toString();
                clienteRelacionado = Integer.parseInt(t);
            }
            
            

            
            String f = (String) cboxCompraFacturas.getSelectedItem();
            char g = f.charAt(0);
            char h = f.charAt(1);
            
            if(Character.isDigit(h)){
                
                s = new StringBuilder().append(g).append(h).toString();
                compraRelacionada = Integer.parseInt(s);
            }
            else{
                s = new StringBuilder().append(g).toString();
                compraRelacionada = Integer.parseInt(s);
            }
            
        if(guardar){
            
           consultasBD consulta = new consultasBD();
           
           facturas factura = new facturas(folioFactura, totalFactura, clienteRelacionado, compraRelacionada);
           consulta.registrarFactura(factura);
           
           txtFacturasFolio.setText("");
           txtFacturasTotal.setText("");

        }
           else{
               JOptionPane.showMessageDialog(null, mensaje);
           }
     }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       } 
    }//GEN-LAST:event_btnFacturasRegistrarActionPerformed

    private void cboxFacturasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxFacturasClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxFacturasClienteActionPerformed

    private void cboxFacturasClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxFacturasClienteMouseClicked
        // TODO add your handling code here:
        String mensaje = "";
        
        try{
        consultasBD cargarComboBox = new consultasBD();
        cboxFacturasCliente.removeAllItems();
        cargarComboBox.consultaClientes(cboxFacturasCliente);
        if(cboxFacturasCliente.getItemCount() == 0){
            mensaje = "Es necesario capturar primero el cliente";
            JOptionPane.showMessageDialog(null, mensaje);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_cboxFacturasClienteMouseClicked

    private void cboxCompraFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCompraFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCompraFacturasActionPerformed

    private void cboxCompraFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxCompraFacturasMouseClicked
        // TODO add your handling code here:
        
        String mensaje = "";
        
        try{
        consultasBD cargarComboBox = new consultasBD();
        cboxCompraFacturas.removeAllItems();
        cargarComboBox.consultaCompras(cboxCompraFacturas);
        if(cboxCompraFacturas.getItemCount() == 0){
            mensaje = "Es necesario capturar primero la compra";
            JOptionPane.showMessageDialog(null, mensaje);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cboxCompraFacturasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(capturaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(capturaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(capturaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(capturaFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new capturaFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacturasCerrar;
    private javax.swing.JButton btnFacturasRegistrar;
    private javax.swing.JComboBox<String> cboxCompraFacturas;
    private javax.swing.JComboBox<String> cboxFacturasCliente;
    private javax.swing.JLabel lblFacturaCompra;
    private javax.swing.JLabel lblFacturasCliente;
    private javax.swing.JLabel lblFacturasFolio;
    private javax.swing.JLabel lblFacturasTitulo;
    private javax.swing.JLabel lblFacturasTotal;
    private javax.swing.JTextField txtFacturasFolio;
    private javax.swing.JTextField txtFacturasTotal;
    // End of variables declaration//GEN-END:variables
}
