/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazModulosCaptura;

import clases.calculos;
import clases.compras;
import clases.pagos;
import conexion.consultasBD;
import javax.swing.JOptionPane;

/**
 *
 * @author bruce
 */
public class capturaPagos extends javax.swing.JFrame {

    /**
     * Creates new form capturaPagos
     */
    public capturaPagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPagosTitulo = new javax.swing.JLabel();
        lblPagosCompra = new javax.swing.JLabel();
        lblPagosMoneda = new javax.swing.JLabel();
        lblPagosMontoPagado = new javax.swing.JLabel();
        lblPagosFactura = new javax.swing.JLabel();
        lblPagosTC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPagosMoneda = new javax.swing.JList<>();
        txtPagosMontoPagado = new javax.swing.JTextField();
        txtPagosFecha = new javax.swing.JTextField();
        lblPagosFecha = new javax.swing.JLabel();
        cboxPagosFactura = new javax.swing.JComboBox<>();
        txtPagosTC = new javax.swing.JTextField();
        lblPagosMontoDLS = new javax.swing.JLabel();
        txtPagosMontoDLS = new javax.swing.JTextField();
        btnPagosRegistrar = new javax.swing.JButton();
        btnPagosCerrar = new javax.swing.JButton();
        cboxPagosCompra = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPagosTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblPagosTitulo.setText("Registro de Pagos");

        lblPagosCompra.setText("Compra Relacionada:");

        lblPagosMoneda.setText("Moneda:");

        lblPagosMontoPagado.setText("Monto Pagado:");

        lblPagosFactura.setText("Factura Relacionada:");

        lblPagosTC.setText("T.C.");

        listPagosMoneda.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pesos", "Dolares" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPagosMoneda);

        txtPagosMontoPagado.setEditable(false);
        txtPagosMontoPagado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPagosMontoPagadoMouseClicked(evt);
            }
        });
        txtPagosMontoPagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagosMontoPagadoActionPerformed(evt);
            }
        });

        lblPagosFecha.setText("Fecha de Pago:");

        cboxPagosFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxPagosFacturaMouseClicked(evt);
            }
        });
        cboxPagosFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPagosFacturaActionPerformed(evt);
            }
        });

        lblPagosMontoDLS.setText("Monto Pagado en Dls:");

        txtPagosMontoDLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagosMontoDLSActionPerformed(evt);
            }
        });

        btnPagosRegistrar.setText("Registrar");
        btnPagosRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosRegistrarActionPerformed(evt);
            }
        });

        btnPagosCerrar.setText("Cerrar");
        btnPagosCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosCerrarActionPerformed(evt);
            }
        });

        cboxPagosCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboxPagosCompraMouseClicked(evt);
            }
        });
        cboxPagosCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPagosCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPagosTitulo)
                .addGap(223, 223, 223))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPagosRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnPagosCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPagosMontoPagado)
                                .addGap(18, 18, 18)
                                .addComponent(txtPagosMontoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPagosFecha)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPagosCompra)
                                    .addComponent(lblPagosMoneda))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboxPagosCompra, 0, 127, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblPagosFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboxPagosFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPagosFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPagosTC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPagosTC, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblPagosMontoDLS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPagosMontoDLS)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPagosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagosFecha)
                    .addComponent(txtPagosFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPagosTC)
                            .addComponent(txtPagosTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPagosFactura)
                                .addComponent(cboxPagosFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPagosCompra)
                                .addComponent(cboxPagosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPagosMoneda)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagosMontoPagado)
                    .addComponent(txtPagosMontoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagosMontoDLS)
                    .addComponent(txtPagosMontoDLS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagosRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagosCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPagosMontoDLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagosMontoDLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagosMontoDLSActionPerformed

    private void btnPagosRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosRegistrarActionPerformed
        // TODO add your handling code here:
        Boolean guardar = true;
        String mensaje = "";
        
        try{
            
        String fechaPago = txtPagosFecha.getText();  
        float montoDLS = Float.parseFloat(txtPagosMontoDLS.getText());
        float montoPagado = Float.parseFloat(txtPagosMontoPagado.getText());
        float tipoCambio  = Float.parseFloat(txtPagosTC.getText());
        String moneda = listPagosMoneda.getSelectedValue();

         
       if (fechaPago.length()==0){
            guardar = false;
            mensaje+="Escriba la fecha de pago, por favor\n";
        }
        if (montoDLS==0){
            guardar = false;
            mensaje+="Escriba el monto total en DLS, por favor\n";
        }
        if (montoPagado==0){
            guardar = false;
            mensaje+="Escriba el monto pagado, por favor\n";
        }
        if (tipoCambio==0){
            guardar = false;
            mensaje+="Escriba el tipo de cambio, por favor\n";
        }
        if (moneda.length() == 0){
        guardar = false;
        mensaje+="Seleccione la moneda, por favor\n";
        }

            String c = (String) cboxPagosCompra.getSelectedItem();
            char d = c.charAt(0);
            int compraRelacionada = Character.getNumericValue(d);
            
            String f = (String) cboxPagosFactura.getSelectedItem();
            char g = f.charAt(0);
            int facturaRelacionada = Character.getNumericValue(g);
            
            
        if(guardar){
           consultasBD consulta = new consultasBD();
           
           pagos pago = new pagos(compraRelacionada, (float) montoPagado, facturaRelacionada, fechaPago, moneda, tipoCambio, montoDLS);
                      
           consulta.registrarPago(pago);
           
           txtPagosFecha.setText("");
           txtPagosMontoDLS.setText("");
           txtPagosMontoPagado.setText("");
           txtPagosTC.setText("");
           
        }
           else{
               JOptionPane.showMessageDialog(null, mensaje);
           }
     }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_btnPagosRegistrarActionPerformed

    private void btnPagosCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosCerrarActionPerformed
        // TODO add your handling code here:
        interfazCaptura verformulario = new interfazCaptura();
        
        verformulario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPagosCerrarActionPerformed

    private void cboxPagosCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPagosCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPagosCompraActionPerformed

    private void cboxPagosCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxPagosCompraMouseClicked
        // TODO add your handling code here:
        String mensaje = "";
        
        try{
        consultasBD cargarComboBox = new consultasBD();
        cboxPagosCompra.removeAllItems();
        cargarComboBox.consultaCompras(cboxPagosCompra);
        if(cboxPagosCompra.getItemCount() == 0){
            mensaje = "Es necesario capturar primero la compra";
            JOptionPane.showMessageDialog(null, mensaje);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cboxPagosCompraMouseClicked

    private void cboxPagosFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPagosFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPagosFacturaActionPerformed

    private void cboxPagosFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboxPagosFacturaMouseClicked
        // TODO add your handling code here:
        String mensaje = "";
        
        try{
        consultasBD cargarComboBox = new consultasBD();
        cboxPagosFactura.removeAllItems();
        cargarComboBox.consultaFacturas(cboxPagosFactura);
        if(cboxPagosFactura.getItemCount() == 0){
            mensaje = "Es necesario capturar primero la factura";
            JOptionPane.showMessageDialog(null, mensaje);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cboxPagosFacturaMouseClicked

    private void txtPagosMontoPagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagosMontoPagadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagosMontoPagadoActionPerformed

    private void txtPagosMontoPagadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPagosMontoPagadoMouseClicked
        // TODO add your handling code here:
        calculos conversionTC = new calculos();
       
        try{
        float tipoCambio  = Float.parseFloat(txtPagosTC.getText());
        float montoDLS = Float.parseFloat(txtPagosMontoDLS.getText());
        float resultado = conversionTC.conversionTC(tipoCambio, montoDLS);
        
        String s = Float.toString(resultado);
        
        txtPagosMontoPagado.setText(s);
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtPagosMontoPagadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(capturaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(capturaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(capturaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(capturaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new capturaPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagosCerrar;
    private javax.swing.JButton btnPagosRegistrar;
    private javax.swing.JComboBox<String> cboxPagosCompra;
    private javax.swing.JComboBox<String> cboxPagosFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPagosCompra;
    private javax.swing.JLabel lblPagosFactura;
    private javax.swing.JLabel lblPagosFecha;
    private javax.swing.JLabel lblPagosMoneda;
    private javax.swing.JLabel lblPagosMontoDLS;
    private javax.swing.JLabel lblPagosMontoPagado;
    private javax.swing.JLabel lblPagosTC;
    private javax.swing.JLabel lblPagosTitulo;
    private javax.swing.JList<String> listPagosMoneda;
    private javax.swing.JTextField txtPagosFecha;
    private javax.swing.JTextField txtPagosMontoDLS;
    private javax.swing.JTextField txtPagosMontoPagado;
    private javax.swing.JTextField txtPagosTC;
    // End of variables declaration//GEN-END:variables
}
